#!/bin/bash

status=$(nmcli g | grep -oE "disconnected")
essid=$(nmcli | grep "^wl" | sed 's/\ connected\ to\ //g' | cut -d ':' -f2)

if [ $status ] ; then
    icon=""
    text=""
    col="#575268"
else
    icon=""
    text="${essid}"
    col="#a1bdce"
fi

if [[ "$1" == "--COL" ]]; then
    echo $col	
elif [[ "$1" == "--ESSID" ]]; then
    echo $text
elif [[ "$1" == "--ICON" ]]; then
    echo $icon
fi
