#!/bin/bash

calendar() {
    LOCK_FILE="$HOME/.cache/eww-calendar.lock"

    if [[ ! -f "$LOCK_FILE" ]]; then
        touch "$LOCK_FILE"
        eww open calendar
    else
        eww close calendar
        rm "$LOCK_FILE"
    fi
}

if [ "$1" = "calendar" ]; then
    calendar
fi
